// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxbfoouxlzyiyniqxqhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YmZvb3V4bHp5aXluaXF4cWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzQxOTEsImV4cCI6MjA3MjExMDE5MX0.5gc62osJhmUmXYbGum02a4RPSy00YEsqWS3_m6qXchg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});